export type ToolCategory = "Memoria" | "Notas" | "PDF" | "IA" | "Contenido" | "Organización" | "Diseño";

export type StudyTool = {
  id: string;
  name: string;
  short: string;
  description: string;
  why: string;
  category: ToolCategory;
  url: string;
  color: string;
  icon: string;
  iconUrl?: string;
  free: boolean;
  featured?: boolean;
};

export const TOOL_CATEGORIES: Array<ToolCategory | "Todas"> = [
  "Todas",
  "Memoria",
  "Notas",
  "PDF",
  "IA",
  "Contenido",
  "Organización",
  "Diseño",
];

export const STUDY_TOOLS: StudyTool[] = [
  {
    id: "anki",
    name: "Anki",
    short: "Repetición espaciada",
    description: "Flashcards inteligentes que te hacen recordar fórmulas, definiciones y teoremas justo cuando estás por olvidarlos.",
    why: "Ideal para memorizar identidades trigonométricas, constantes físicas y vocabulario de Humanidades.",
    category: "Memoria",
    url: "https://apps.ankiweb.net/",
    color: "#1f6feb",
    icon: "anki",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Anki-icon.svg/1280px-Anki-icon.svg.png",
    free: true,
    featured: true,
  },
  {
    id: "pdf-annotator",
    name: "PDF Annotator",
    short: "Marca y resuelve",
    description: "Anota, resalta y escribe sobre separatas y exámenes PDF sin imprimir. Perfecto para practicar sobre el papel digital.",
    why: "Úsalo para resolver exámenes reales de la UNI y dejar notas al margen de cada error.",
    category: "PDF",
    url: "https://www.facebook.com/PDFAnnotator/",
    color: "#e85d04",
    icon: "pdf",
    iconUrl: "https://www.google.com/s2/favicons?domain=pdfannotator.com&sz=128",
    free: false,
  },
  {
    id: "onenote",
    name: "OneNote",
    short: "Cuaderno digital",
    description: "Organiza todo tu material por curso, fecha y tema. Soporta escritura a mano, audio y capturas de pantalla.",
    why: "Crea un cuaderno por área: Matemática, Física, Química, Aptitud y Humanidades.",
    category: "Notas",
    url: "https://es.wikipedia.org/wiki/Microsoft_OneNote",
    color: "#7719aa",
    icon: "onenote",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Microsoft_OneNote_Icon_%282025_-_present%29.svg/250px-Microsoft_OneNote_Icon_%282025_-_present%29.svg.png",
    free: true,
    featured: true,
  },
  {
    id: "inkodo",
    name: "Inkodo",
    short: "Pizarra a mano",
    description: "Pizarra digital ligera para resolver problemas a mano, dibujar diagramas y explicar pasos como en el pizarrón.",
    why: "Perfecta para practicar desarrollos de Física y Geometría con lápiz digital.",
    category: "Notas",
    url: "https://apps.microsoft.com/detail/9nblggh4s50q?hl=es-ES&gl=ES",
    color: "#0d9488",
    icon: "inkodo",
    iconUrl: "https://store-images.s-microsoft.com/image/apps.34000.13510798887562925.2ac53b6e-5041-4dbe-88b5-591b4d37ebd2.71d8d553-b22a-46cd-8791-f0d358fc0593",
    free: true,
  },
  {
    id: "tiktok",
    name: "TikTok",
    short: "Microclases",
    description: "Tips rápidos, trucos de método y motivaciones cortas. Úsalo con disciplina: 15 minutos, no 2 horas.",
    why: "Busca explicaciones rápidas de temas que no te salen y vuelve a tu práctica.",
    category: "Contenido",
    url: "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically&hl=es_419",
    color: "#fe2c55",
    icon: "tiktok",
    iconUrl: "https://cdn.simpleicons.org/tiktok/ffffff",
    free: true,
  },
  {
    id: "youtube",
    name: "YouTube",
    short: "Clases completas",
    description: "El aula infinita: canales de Física, Matemática y Química nivel UNI con resoluciones completas.",
    why: "Combínalo con la sección Guía de CachimboUNI para no perderte entre miles de videos.",
    category: "Contenido",
    url: "https://es.wikipedia.org/wiki/Archivo:Youtube_logo.png",
    color: "#ff0000",
    icon: "youtube",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/250px-YouTube_full-color_icon_%282017%29.svg.png",
    free: true,
    featured: true,
  },
  {
    id: "sketchio",
    name: "Sketch.IO",
    short: "Diagramas y esquemas",
    description: "Crea esquemas, mapas mentales y dibujos técnicos en segundos. Exporta y pégalos en tus apuntes.",
    why: "Útil para diagramas de cuerpo libre, circuitos y mapas de procesos químicos.",
    category: "Diseño",
    url: "https://sketch.io/sketchpad/",
    color: "#f59e0b",
    icon: "sketch",
    iconUrl: "https://www.google.com/s2/favicons?domain=sketch.io&sz=128",
    free: true,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    short: "Referencias visuales",
    description: "Tableros de fórmulas, resúmenes visuales y esquemas. Guarda solo lo que vas a usar esta semana.",
    why: "Crea un board por curso y guarda solo resúmenes limpios y legibles.",
    category: "Contenido",
    url: "https://www.pinterest.com/",
    color: "#e60023",
    icon: "pinterest",
    iconUrl: "https://cdn.simpleicons.org/pinterest/e60023",
    free: true,
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    short: "Tutor 24/7",
    description: "Explica conceptos, corrige desarrollos y genera problemas similares. No copies: pide que te guíe paso a paso.",
    why: "Pídele: “explícame este error sin darme la respuesta final” para entrenar criterio.",
    category: "IA",
    url: "https://chatgpt.com/",
    color: "#10a37f",
    icon: "chatgpt",
    iconUrl: "https://cdn.simpleicons.org/openai/ffffff",
    free: true,
    featured: true,
  },
  {
    id: "gemini",
    name: "Gemini",
    short: "IA de Google",
    description: "Analiza PDFs, resúmenes y búsquedas. Útil para entender enunciados largos y organizar temarios.",
    why: "Sube un PDF de teoría y pide un mapa de temas clave antes de estudiar.",
    category: "IA",
    url: "https://gemini.google.com/",
    color: "#4285f4",
    icon: "gemini",
    iconUrl: "https://cdn.simpleicons.org/googlegemini/4285f4",
    free: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    short: "Razonamiento fuerte",
    description: "Modelo potente para razonamiento matemático y pasos de solución. Excelente para verificar lógica.",
    why: "Úsalo para revisar si tu método de resolución es sólido, no solo el resultado.",
    category: "IA",
    url: "https://chat.deepseek.com/",
    color: "#4d6bfe",
    icon: "deepseek",
    iconUrl: "https://cdn.simpleicons.org/deepseek/4d6bfe",
    free: true,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    short: "Ritmo y disciplina",
    description: "Planifica bloques de estudio, simulacros y descansos. Sin calendario, el esfuerzo se dispersa.",
    why: "Agenda 3 bloques diarios: teoría, práctica y revisión. Bloquea el celular en ese horario.",
    category: "Organización",
    url: "https://calendar.google.com/",
    color: "#0f9d58",
    icon: "calendar",
    iconUrl: "https://cdn.simpleicons.org/googlecalendar/4285f4",
    free: true,
    featured: true,
  },
];

export const PROJECT_TOOLS: StudyTool[] = [
  {
    id: "calculadora-admision-uni",
    name: "Calculadora Admisión UNI",
    short: "Calcula tu puntaje",
    description: "Herramienta directa para estimar tu puntaje de admisión UNI y proyectar cuánto necesitas mejorar.",
    why: "Úsala después de cada simulacro para convertir tus aciertos y errores en una meta concreta.",
    category: "Organización",
    url: "https://calculadoraadmisionuni.netlify.app",
    color: "#d8763e",
    icon: "calculator",
    iconUrl: "https://www.google.com/s2/favicons?domain=calculadoraadmisionuni.netlify.app&sz=128",
    free: true,
    featured: true,
  },
  {
    id: "desmos",
    name: "Desmos",
    short: "Calculadora gráfica",
    description: "Grafica funciones, compara ecuaciones y entiende visualmente transformaciones algebraicas.",
    why: "Comprueba dominios, rangos, intersecciones y comportamiento de funciones sin perder tiempo dibujando.",
    category: "Diseño",
    url: "https://www.desmos.com/calculator?lang=es",
    color: "#2d9d55",
    icon: "calculator",
    iconUrl: "https://www.google.com/s2/favicons?domain=desmos.com&sz=128",
    free: true,
    featured: true,
  },
  {
    id: "geogebra",
    name: "GeoGebra Classic",
    short: "Geometría dinámica",
    description: "Construye figuras, visualiza lugares geométricos y conecta álgebra, cálculo y geometría.",
    why: "Ideal para comprobar propiedades, explorar construcciones y entender por qué funciona un teorema.",
    category: "Diseño",
    url: "https://www.geogebra.org/classic?lang=es",
    color: "#6557d2",
    icon: "geogebra",
    iconUrl: "https://www.google.com/s2/favicons?domain=geogebra.org&sz=128",
    free: true,
  },
  {
    id: "merriam-webster",
    name: "Merriam-Webster",
    short: "Diccionario inglés",
    description: "Diccionario, pronunciación, ejemplos y sinónimos para fortalecer vocabulario y comprensión en inglés.",
    why: "Consulta palabras del temario y crea flashcards en Anki con definición, audio y una oración propia.",
    category: "Contenido",
    url: "https://www.merriam-webster.com/",
    color: "#c71920",
    icon: "dictionary",
    iconUrl: "https://www.google.com/s2/favicons?domain=merriam-webster.com&sz=128",
    free: true,
  },
  {
    id: "lingua",
    name: "Lingua.com",
    short: "Comprensión lectora",
    description: "Textos por nivel con preguntas para practicar comprensión lectora en español e inglés.",
    why: "Haz una lectura corta diaria y responde sin traducir palabra por palabra para ganar velocidad.",
    category: "Contenido",
    url: "https://lingua.com/es/",
    color: "#1976d2",
    icon: "language",
    iconUrl: "https://www.google.com/s2/favicons?domain=lingua.com&sz=128",
    free: true,
  },
  {
    id: "iedra",
    name: "Iedra",
    short: "Recursos de lengua",
    description: "Plataforma de consulta y recursos lingüísticos para trabajar vocabulario, redacción y análisis del idioma.",
    why: "Úsala como apoyo para Lenguaje y Razonamiento Verbal cuando una definición o uso no esté claro.",
    category: "Contenido",
    url: "https://iedra.es/",
    color: "#b6923b",
    icon: "dictionary",
    iconUrl: "https://www.google.com/s2/favicons?domain=iedra.es&sz=128",
    free: true,
  },
];
