-- ============================================================
--  CachimboUNI · Datos iniciales (seed)
--  Generado automáticamente con `node scripts/generate-seed.mjs`.
--  Ejecútalo en el SQL Editor después de `supabase/schema.sql`.
--  Es idempotente: puedes ejecutarlo varias veces sin errores.
-- ============================================================

-- Categorías y sus colecciones
insert into public.categories (id, sort_index, name, tagline, description, bullets, icon, external_url, position) values ('teoria', '01', 'Teoría', 'Recolección de recursos', 'Reuní en un solo lugar las carpetas y blogs más útiles con teoría y material para el examen de la UNI. Cada enlace abre en una pestaña nueva.', '["5 fuentes curadas","Drives oficiales y comunidad","Acceso directo sin login"]'::jsonb, 'theory', 'https://drive.google.com/drive/folders/1eaznZqhy1ZHaa-cZYq4Cwg55dJ7RDgBw?usp=drive_link', 0)
  on conflict (id) do update set sort_index = excluded.sort_index, name = excluded.name, tagline = excluded.tagline, description = excluded.description, bullets = excluded.bullets, icon = excluded.icon, external_url = excluded.external_url, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('col-01', 'teoria', 'Banco de Teoría UNI · Tomo I', 'Carpeta Drive con separatas y temas base organizados por curso para la preparación.', 'https://drive.google.com/drive/folders/1wvSa5LnIIR6tJa6N83kjmzVv2ApC3sOi', 'drive', null, 0)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('col-02', 'teoria', 'Banco de Teoría UNI · Tomo II', 'Segunda carpeta Drive con material complementario, apuntes y teoría avanzada.', 'https://drive.google.com/drive/u/0/folders/1Mn_zvTYOMuE034l92NzXv0obgKLV-J8u', 'drive', null, 1)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('col-03', 'teoria', 'Yachakaj · Blog educativo', 'Apuntes, resoluciones y artículos por curso publicados por la comunidad preuniversitaria.', 'https://yachakaj.blogspot.com/', 'blog', null, 2)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('col-04', 'teoria', 'Separatas por cursos · Ciencias', 'Material de Física, Química y Matemática en formato PDF dentro de Drive.', 'https://drive.google.com/drive/u/0/folders/1TlA14SIObl3L4w4FmC2pyFWVU30QJePA', 'drive', null, 3)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('col-05', 'teoria', 'Compendios y guías resueltas', 'Guías y compendios con desarrollo paso a paso para consulta rápida antes del examen.', 'https://drive.google.com/drive/u/0/folders/1v6X_dEHhY_zGFJ8gmvHKvodFTNLXAcnE', 'drive', null, 4)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.categories (id, sort_index, name, tagline, description, bullets, icon, external_url, position) values ('examenes', '02', 'Exámenes', 'Banco de Evaluaciones', 'Colección completa de Drives con simulacros y exámenes pasados resueltos para entrenar bajo las condiciones del examen real.', '["4 carpetas Drive","Estructura de las 3 pruebas","Material oficial y solucionarios"]'::jsonb, 'exam', 'https://drive.google.com/drive/u/0/folders/1I23XDpAKvdsbAHGWBw_yi_id0FMwiN-K', 1)
  on conflict (id) do update set sort_index = excluded.sort_index, name = excluded.name, tagline = excluded.tagline, description = excluded.description, bullets = excluded.bullets, icon = excluded.icon, external_url = excluded.external_url, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('exam-01', 'examenes', 'Simulacros y Exámenes UNI · Tomo I', 'Carpeta de Google Drive con simulacros completos, claves y solucionarios de procesos de admisión recientes.', 'https://drive.google.com/drive/u/0/folders/1I23XDpAKvdsbAHGWBw_yi_id0FMwiN-K', 'drive', null, 0)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('exam-02', 'examenes', 'Exámenes de Admisión UNI · Tomo II', 'Colección adicional de exámenes históricos resueltos paso a paso por profesores especialistas.', 'https://drive.google.com/drive/folders/1a1o0OYw7xx6gYS8YS_LZns2gIYeYgoqT', 'drive', null, 1)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('exam-03', 'examenes', 'Materiales Destacados y Claves (Drive)', 'Enlace directo a tu panel de carpetas destacadas con solucionarios rápidos y resúmenes de fórmulas.', 'https://drive.google.com/drive/starred?hl=es-419', 'drive', null, 2)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('exam-04', 'examenes', 'Pruebas de Admisión por Cursos', 'Pruebas clasificadas y separadas para que midas tu nivel en ciencias, matemática y aptitud.', 'https://drive.google.com/drive/folders/1PYax2odHKNtvFf21Xll5_i6GoX5I__Da', 'drive', null, 3)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.categories (id, sort_index, name, tagline, description, bullets, icon, external_url, position) values ('libros', '03', 'Libros', 'Textos Recomendados', 'Bibliotecas organizadas con libros esenciales y compendios académicos completos para profundizar en cada área de estudio.', '["3 colecciones masivas","Física, Química y Matemáticas","Lecturas selectas y solucionarios"]'::jsonb, 'book', 'https://drive.google.com/drive/folders/1i-9wE3_GtGDhm_WdkgU13uF_Z_0WjC-f?hl=es-419', 2)
  on conflict (id) do update set sort_index = excluded.sort_index, name = excluded.name, tagline = excluded.tagline, description = excluded.description, bullets = excluded.bullets, icon = excluded.icon, external_url = excluded.external_url, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('lib-01', 'libros', 'Biblioteca de Libros UNI · Tomo I', 'Compendios de teoría y problemas selectos de Álgebra, Aritmética, Geometría y Trigonometría.', 'https://drive.google.com/drive/folders/1i-9wE3_GtGDhm_WdkgU13uF_Z_0WjC-f?hl=es-419', 'drive', null, 0)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('lib-02', 'libros', 'Biblioteca de Libros UNI · Tomo II', 'Textos de Física general, Química inorgánica y orgánica para postulantes preuniversitarios de la UNI.', 'https://drive.google.com/drive/folders/1xji4_EXTsWbluFEKcjY39-WYFJ8TXCk6?hl=es-419', 'drive', null, 1)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('lib-03', 'libros', 'Colección de Compendios y Lecturas', 'Compendio completo de Humanidades, lenguaje, razonamiento verbal y cultura general.', 'https://drive.google.com/drive/folders/1H5GjViDLbrkOp4I3RJzrJw1BK_7yh7_Y?hl=es-419', 'drive', null, 2)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.categories (id, sort_index, name, tagline, description, bullets, icon, external_url, position) values ('videos', '04', 'Videos', 'CEPRELIBRE', 'Playlists de YouTube organizadas por curso para aprender viendo. Clases completas de CEPRELIBRE con teoría y ejercicios resueltos.', '["6 cursos en video","Clases completas gratis","Teoría y práctica juntas"]'::jsonb, 'play', 'https://www.youtube.com/playlist?list=PLZZWh41GUPsFdJ5C-RnMtzEtgWcemXByQ', 3)
  on conflict (id) do update set sort_index = excluded.sort_index, name = excluded.name, tagline = excluded.tagline, description = excluded.description, bullets = excluded.bullets, icon = excluded.icon, external_url = excluded.external_url, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-01', 'videos', 'Álgebra', 'Playlist completa de Álgebra: teoría de exponentes, polinomios, ecuaciones y sistemas explicados en video.', 'https://www.youtube.com/playlist?list=PLZZWh41GUPsFdJ5C-RnMtzEtgWcemXByQ', 'playlist', null, 0)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-02', 'videos', 'Física', 'Clases grabadas de Física con desarrollo de problemas tipo admisión paso a paso.', 'https://www.youtube.com/playlist?list=PLZZWh41GUPsFxVK1oMotXsPP3F4Vp0LNU', 'playlist', null, 1)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-03', 'videos', 'Química', 'Serie completa de Química: estructura atómica, enlace, estequiometría y más.', 'https://www.youtube.com/playlist?list=PLZZWh41GUPsGvxutb8VAIihGO91pABB93', 'playlist', null, 2)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-04', 'videos', 'Aritmética', 'Playlist de Aritmética con divisibilidad, razones, proporciones y teoría de números.', 'https://www.youtube.com/playlist?list=PLZZWh41GUPsHQ70zXO4BdFMTEVSbwFLRD', 'playlist', null, 3)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-05', 'videos', 'Trigonometría', 'Razones trigonométricas, identidades y circunferencia trigonométrica en video.', 'https://www.youtube.com/watch?v=c_iR35iHETM&list=PLuuOG0qft5YQusuDF4Ev3X60GvjjuOPzs&index=4', 'playlist', null, 4)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;
insert into public.collections (id, category_id, title, description, url, type, subject, position) values ('vid-06', 'videos', 'Geometría', 'Triángulos, circunferencia, áreas y sólidos desarrollados con gráficos claros.', 'https://www.youtube.com/watch?v=rl_20TNotZg&list=PLuuOG0qft5YQusuDF4Ev3X60GvjjuOPzs&index=4', 'playlist', null, 5)
  on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, description = excluded.description, url = excluded.url, type = excluded.type, subject = excluded.subject, position = excluded.position;

-- Recursos (materiales individuales)
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-01', 'teoria', 'Matemática', 'Álgebra desde cero', 'Construye la base algebraica que sostiene todo el examen: del lenguaje simbólico a los sistemas de ecuaciones.', 'Básico', '{"label":"Capítulos","value":"12"}'::jsonb, '{"label":"Duración","value":"9 h"}'::jsonb, '["Productos notables","Factorización","Ecuaciones","Inecuaciones","Sistemas"]'::jsonb, null, null, true, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-02', 'teoria', 'Matemática', 'Geometría plana y del espacio', 'Teoremas ordenados por familia, con estrategias de trazo auxiliar y cálculo de áreas y volúmenes.', 'Intermedio', '{"label":"Capítulos","value":"14"}'::jsonb, '{"label":"Duración","value":"11 h"}'::jsonb, '["Triángulos","Circunferencia","Áreas","Sólidos","Semejanza"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-03', 'teoria', 'Matemática', 'Trigonometría aplicada', 'De la circunferencia trigonométrica a las identidades y ecuaciones que aparecen año tras año en la prueba de Matemática.', 'Intermedio', '{"label":"Capítulos","value":"10"}'::jsonb, '{"label":"Duración","value":"7 h"}'::jsonb, '["Razones","Identidades","C.T.","Ecuaciones","Resolución de triángulos"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-04', 'teoria', 'Física', 'Mecánica clásica esencial', 'Cinemática, estática y dinámica explicadas con diagramas de cuerpo libre y método de resolución uniforme.', 'Intermedio', '{"label":"Capítulos","value":"11"}'::jsonb, '{"label":"Duración","value":"10 h"}'::jsonb, '["Cinemática","Estática","Dinámica","Trabajo y energía","Momentum"]'::jsonb, null, null, true, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-05', 'teoria', 'Física', 'Electricidad y magnetismo', 'Campo, potencial y circuitos con el enfoque conceptual que la UNI evalúa en la tercera prueba.', 'Avanzado', '{"label":"Capítulos","value":"9"}'::jsonb, '{"label":"Duración","value":"8 h"}'::jsonb, '["Electrostática","Circuitos","Campo magnético","Inducción"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-06', 'teoria', 'Química', 'Materia, átomo y enlace', 'Fundamentos de estructura atómica y enlace químico con tablas de apoyo y errores frecuentes señalados.', 'Básico', '{"label":"Capítulos","value":"8"}'::jsonb, '{"label":"Duración","value":"6 h"}'::jsonb, '["Estructura atómica","Tabla periódica","Enlace","Nomenclatura"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-07', 'teoria', 'Química', 'Estequiometría y soluciones', 'El corazón cuantitativo de Química: mol, reacciones, rendimiento y unidades de concentración.', 'Intermedio', '{"label":"Capítulos","value":"7"}'::jsonb, '{"label":"Duración","value":"6 h"}'::jsonb, '["Mol","Reacciones","Rendimiento","Molaridad","Gases"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-08', 'teoria', 'Aptitud', 'Razonamiento matemático con método', 'Estrategias de conteo, orden de información y planteo de ecuaciones para resolver rápido y sin dudar.', 'Intermedio', '{"label":"Capítulos","value":"10"}'::jsonb, '{"label":"Duración","value":"7 h"}'::jsonb, '["Planteo","Sucesiones","Conteo","Certezas","Cronometría"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('t-09', 'teoria', 'Humanidades', 'Comprensión lectora y lenguaje', 'Técnicas de lectura activa, jerarquía de ideas y precisión léxica para la primera prueba.', 'Básico', '{"label":"Capítulos","value":"9"}'::jsonb, '{"label":"Duración","value":"5 h"}'::jsonb, '["Ideas principales","Inferencias","Conectores","Ortografía","Sintaxis"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-01', 'examenes', 'Matemática', 'Examen de admisión 2026-I · Prueba de Matemática', 'Segunda prueba del proceso 2026-I con solucionario completo y clasificación por tema y dificultad.', 'Avanzado', '{"label":"Preguntas","value":"40"}'::jsonb, '{"label":"Tiempo","value":"3 h"}'::jsonb, '["Aritmética","Álgebra","Geometría","Trigonometría"]'::jsonb, null, 2026, true, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-02', 'examenes', 'Física', 'Examen de admisión 2026-I · Física y Química', 'Tercera prueba del proceso 2026-I resuelta con desarrollo completo y comentarios de estrategia.', 'Avanzado', '{"label":"Preguntas","value":"40"}'::jsonb, '{"label":"Tiempo","value":"3 h"}'::jsonb, '["Mecánica","Electricidad","Estequiometría","Gases"]'::jsonb, null, 2026, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-03', 'examenes', 'Aptitud', 'Examen de admisión 2026-I · Aptitud y Humanidades', 'Primera prueba del proceso con claves comentadas de razonamiento verbal, matemático y cultura general.', 'Intermedio', '{"label":"Preguntas","value":"40"}'::jsonb, '{"label":"Tiempo","value":"3 h"}'::jsonb, '["R. Verbal","R. Matemático","Historia","Actualidad"]'::jsonb, null, 2026, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-04', 'examenes', 'Matemática', 'Examen de admisión 2025-II · Prueba de Matemática', 'Prueba del proceso 2025-II con nivel de exigencia alto en geometría analítica y sucesiones.', 'Avanzado', '{"label":"Preguntas","value":"40"}'::jsonb, '{"label":"Tiempo","value":"3 h"}'::jsonb, '["Analítica","Sucesiones","Números complejos","Áreas"]'::jsonb, null, 2025, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-05', 'examenes', 'Química', 'Banco de Química por temas', 'Preguntas de exámenes anteriores agrupadas por capítulo para reforzar exactamente lo que te falta.', 'Intermedio', '{"label":"Preguntas","value":"180"}'::jsonb, '{"label":"Formato","value":"Por tema"}'::jsonb, '["Enlace","Mol","Redox","Orgánica"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-06', 'examenes', 'Matemática', 'Simulacro cronometrado N.º 1', 'Simulacro completo con la estructura de las tres pruebas y hoja de resultados para medir tu puntaje.', 'Avanzado', '{"label":"Preguntas","value":"120"}'::jsonb, '{"label":"Tiempo","value":"9 h"}'::jsonb, '["Simulacro","Tres pruebas","Puntaje","Ranking"]'::jsonb, null, null, true, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-07', 'examenes', 'Física', 'Problemas UNI de Física 2018-2025', 'Compilado histórico de problemas de Física ordenados por frecuencia de aparición en el examen.', 'Avanzado', '{"label":"Problemas","value":"240"}'::jsonb, '{"label":"Periodo","value":"2018-2025"}'::jsonb, '["Cinemática","Dinámica","Ondas","Termodinámica"]'::jsonb, null, 2025, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('e-08', 'examenes', 'Humanidades', 'Práctica dirigida de Humanidades', 'Ejercicios de literatura, historia, geografía y actualidad con explicación de cada alternativa.', 'Intermedio', '{"label":"Preguntas","value":"90"}'::jsonb, '{"label":"Tiempo","value":"2 h"}'::jsonb, '["Literatura","Historia","Geografía","Economía"]'::jsonb, null, null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-01', 'libros', 'Matemática', 'Álgebra · Colección clásica', 'Texto de referencia para dominar teoría de exponentes, polinomios y sistemas con miles de ejercicios.', 'Intermedio', '{"label":"Páginas","value":"560"}'::jsonb, '{"label":"Ejercicios","value":"1 800+"}'::jsonb, '["Exponentes","Polinomios","Matrices","Determinantes"]'::jsonb, 'Compendio académico', null, true, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-02', 'libros', 'Matemática', 'Geometría · Teoría y problemas', 'Un recorrido completo por la geometría del plano y del espacio con problemas de nivel UNI.', 'Avanzado', '{"label":"Páginas","value":"480"}'::jsonb, '{"label":"Ejercicios","value":"1 200+"}'::jsonb, '["Triángulos","Cuadriláteros","Poliedros","Superficies"]'::jsonb, 'Compendio académico', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-03', 'libros', 'Física', 'Física general para postulantes', 'Base conceptual sólida con problemas graduados desde el nivel escolar hasta el nivel de admisión.', 'Intermedio', '{"label":"Páginas","value":"620"}'::jsonb, '{"label":"Ejercicios","value":"1 500+"}'::jsonb, '["Mecánica","Calor","Ondas","Electromagnetismo"]'::jsonb, 'Texto universitario', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-04', 'libros', 'Química', 'Química: principios y problemas', 'Estructura atómica, reacciones y cálculos químicos explicados con el rigor que exige la UNI.', 'Intermedio', '{"label":"Páginas","value":"440"}'::jsonb, '{"label":"Ejercicios","value":"900+"}'::jsonb, '["Átomo","Enlace","Estequiometría","Orgánica"]'::jsonb, 'Texto universitario', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-05', 'libros', 'Aptitud', 'Razonamiento matemático integral', 'Colección de problemas de ingenio y método con soluciones comentadas para ganar velocidad.', 'Intermedio', '{"label":"Páginas","value":"380"}'::jsonb, '{"label":"Ejercicios","value":"1 100+"}'::jsonb, '["Ingenio","Operadores","Conteo","Probabilidades"]'::jsonb, 'Compendio académico', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-06', 'libros', 'Humanidades', 'Compendio de Humanidades', 'Todo el temario de la primera prueba en un solo volumen: lenguaje, literatura, historia y sociedad.', 'Básico', '{"label":"Páginas","value":"520"}'::jsonb, '{"label":"Unidades","value":"24"}'::jsonb, '["Lenguaje","Literatura","Historia","Cívica","Actualidad"]'::jsonb, 'Compendio académico', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
insert into public.resources (id, category, subject, title, summary, level, primary_, secondary_, topics, author, year, highlight, position) values ('l-07', 'libros', 'Matemática', 'Aritmética razonada', 'Teoría de números, razones y proporciones con enfoque de resolución rápida para el examen.', 'Básico', '{"label":"Páginas","value":"410"}'::jsonb, '{"label":"Ejercicios","value":"1 000+"}'::jsonb, '["Divisibilidad","Proporciones","Porcentajes","Estadística"]'::jsonb, 'Compendio académico', null, false, 0)
  on conflict (id) do update set category = excluded.category, subject = excluded.subject, title = excluded.title, summary = excluded.summary, level = excluded.level, primary_ = excluded.primary_, secondary_ = excluded.secondary_, topics = excluded.topics, author = excluded.author, year = excluded.year, highlight = excluded.highlight, position = excluded.position;
